### ISSUE TITLE
Possibble to start/stop another program when window changes view?

### ISSUE THREAD

**Issue by jasondavis** [miabrahams/VirtuaWin#2]
My boss is requiring me to run a program that monitors my mouse, keyword movement for activity and also send random interval screenshots.  I have 3 monitors and it sends all 3 as 1 wide screenshot.

I would love to be able to build a module of some sort for VirtualWin that would basically "click" the Pause button on the monitoring software when I switch screen views so I can have a screen with sensitive items like email that I do not want uploaded to my boss!

Do you think such a feature is even possible?

**Comment by miabrahams** [comment]
Hi Jason,

I am not working on this project anymore since switching to Windows 10, which implements native virtual desktops.  Such a thing is possible but it would not be a trivial change.  An easier solution may be to use software like AutoHotkey, could provide an automated command like the one you described.
